/*
 *  PSTypes.h
 *  Phonosynth
 *
 *  Created by Greg on 10/31/08.
 *  Copyright 2008 Brown University. All rights reserved.
 *
 */

#ifndef _PSTYPES_H_
#define _PSTYPES_H_

enum
PhonosynthMode
{
	MODE_NORMAL,
	MODE_SLIDESHOW_PLAYING,
	MODE_SLIDESHOW_PAUSED,	
	MODE_PANORAMA,
	MODE_ARCBALL,
    MODE_NONE
};

enum ButtonID
{
    ID_LOGO,
    ID_OPEN,
    ID_SETTINGS,	
    ID_SLIDESHOW,
    ID_LEFTARROW,		
    ID_RIGHTARROW,		
    ID_UPARROW,
    ID_DOWNARROW,
    ID_INARROW,
    ID_OUTARROW,
    ID_CONFIDENTIAL,
    ID_POINTCLOUD,
    ID_ARCBALL,
    ID_SLIDESHOW_PLAY,
    ID_SLIDESHOW_PAUSE,
    ID_SLIDESHOW_STOP,
    ID_SHOW_BUTTONS,
    ID_HIDE_BUTTONS,
	ID_SHOW_RECTS,
	ID_HIDE_RECTS,
    ID_TOGGLE_IMAGES,	
    ID_TOGGLE_CONES,
    ID_LANDSCAPE,
    ID_PORTRAIT,
	ID_HELP,
	ID_ARCBALL_EXIT,
	ID_SLIDESHOW_NEXT,
	ID_SLIDESHOW_PREV,
	ID_NEXT_3D_GROUP
};

enum ButtonGroupID
{
    BUTTONS_NORMAL_CONTROL, 
    BUTTONS_ARCBALL_CONTROL,    
    BUTTONS_SLIDESHOW_CONTROL,
	BUTTONS_NORMAL_MENU,
    BUTTONS_SLIDESHOW_MENU,
	BUTTONS_ARCBALL_MENU,
	BUTTONS_DESCRIPTION_LABELS,
    BUTTONS_OTHER
};

enum DrawPriorities
{
    PRIORITY_FIRST         = 0,
    PRIORITY_PC_GROUP      = 1,
    PRIORITY_PC            = 2,    
    PRIORITY_QUAD_GROUP    = 3,
    PRIORITY_QUAD_NEIGHBOR = 4,
    PRIORITY_QUAD_MAIN     = 5,
    PRIORITY_CC_GROUP      = 6,
    PRIORITY_CC            = 7,
	PRIORITY_QRECT_GROUP   = 8,
	PRIORITY_QRECT		   = 9,
    PRIORITY_LAST          = 10
};


enum ScreenOrientation
{
    SCREEN_ORIENTATION_PORTRAIT,
	SCREEN_ORIENTATION_LANDSCAPE,
	SCREEN_ORIENTATION_PORTRAIT_REV,
	SCREEN_ORIENTATION_LANDSCAPE_REV
};


enum ImagePriority
{
	IPRIORITY_LOWEST,
	IPRIORITY_NEIGHBOR,
	IPRIORITY_PEER,
	IPRIORITY_MAIN_IMAGE,
	IPRIORITY_HIGHEST	
};


#endif // _PSTYPES_H_
